### ISSUE TITLE
More fix contact, page...

### ISSUE THREAD

**Issue by ghost** [fictionco/fiction#111]
**After create Contact Forms**
Can not again open and edit is not clickable

**On page in Page Template** after select Basic page can not remove selection add that

**In account Pages** add image and click on image Copy url, not copy url is copy Page Template

**And where upload image?** for avatar and cover better set only one upload or multiple but with select primary

**Comment by arpowers** [comment]
@Sceko ill get right on it. Would it be possible to get screenshots of the issues?

**Comment by ghost** [comment]
![Screenshot 2020-01-16 at 21 13 42](https://user-images.githubusercontent.com/2323952/72559458-1c132f00-38a5-11ea-9767-188281aa522e.png)
Can not again open and edit is not clickable

On page in Page Template after select Basic page can not remove selection add that
![Screenshot 2020-01-16 at 21 14 25](https://user-images.githubusercontent.com/2323952/72559486-2e8d6880-38a5-11ea-9f34-43d7f34673ee.png)

In account Pages add image and click on image Copy url, not copy url is copy Page Template
![Screenshot 2020-01-16 at 21 14 58](https://user-images.githubusercontent.com/2323952/72559521-4369fc00-38a5-11ea-87c8-e27182577b52.png)

And where upload image? for avatar and cover better set only one upload or multiple but with select primary

**Comment by arpowers** [comment]
Good ideas, I'll clean this up tonight

**Comment by ghost** [comment]
And very import for next gen cms is repeat fields in other cms named like matrix fields, flexible content, or like on prismic is named like slices

not using only body with editor stuff and it is it. 

better add blocks like add text, and add gallery, and again add text, add quote etc...  allow users to create repeat fields for content like this 
![Screenshot 2020-01-16 at 23 24 19](https://user-images.githubusercontent.com/2323952/72567976-55549a80-38b7-11ea-9026-e2c64a5ef1c7.png)

plugins its good and i seen you create very nice plugins, but for this cms it's much better to allow users to create a collection with fields and the user can easily create pages, blogs or other stuff without plugins like this 
![Screenshot 2020-01-16 at 23 25 30](https://user-images.githubusercontent.com/2323952/72568059-8634cf80-38b7-11ea-9081-988ea7f8f3ec.png)


And add support for mysql or postgresql in the installation selection

factor cms very nice clean and beautiful design but please no go like other old cms better create collections with this posibility up and in admin panel only add Collections, Content with select Collection and Create Content, Users and Plugins to allowed users create whatever wont. Sorry for my english if some don't understand write.

**Comment by Sceko** [comment]
And fix in last update after add Cover Photo(s) and save nothing save.

**Comment by ghost** [comment]
And fix this  after add **edit** in url like /dashboard/posts/contact-form/edit open this
![Screenshot 2020-01-17 at 00 04 29](https://user-images.githubusercontent.com/2323952/72570361-fa25a680-38bc-11ea-8bbb-1d2b0b33cffb.png)
same for page and other fix that.
And for user Cover Photo(s) after upload and save nothing and remove multiple upload

**Comment by arpowers** [comment]
working on these issues now, are you getting errors thrown in the console?

**Comment by arpowers** [comment]
@Sceko the drag and drop stuff, like prismic, will be accomplished with plugins. We can work on those once we have a stable core :P

**Comment by arpowers** [comment]
I patched a few issues that you described, for anything else, please file 1 issue per bug/request that way we can close them as we fix or address them :)
