### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: JsonWebTokenError: invalid signature     at Object.exports.endpointError

### ISSUE THREAD

**Issue by krlmrr** [fictionco/fiction#112]
**Reason for this issue**

UnhandledPromiseRejectionWarning: Error: JsonWebTokenError: invalid signature
    at Object.exports.endpointError

**Steps to Reproduce**

Create a new project - Start Server, and attempt to go to /dashboard and login.

**Comment by arpowers** [comment]
that's coming from a mismatch with the JWT token.

Is your TOKEN_SECRET set in .env?

**Comment by krlmrr** [comment]
I believe so... 

Sent from my iPhone

> On Jan 15, 2020, at 10:15 PM, Andrew Powers <notifications@github.com> wrote:
> 

﻿
that's coming from a mismatch with the JWT token.

Is your TOKEN_SECRET set in .env?
