### ISSUE TITLE
Contact form

### ISSUE THREAD

**Issue by ghost** [fictionco/fiction#114]
I can not click on contact form and edit is not clickable

![Screenshot 2020-01-17 at 09 45 55](https://user-images.githubusercontent.com/2323952/72597495-3503fa80-390e-11ea-91c9-5ece7a55f09f.png)

**Comment by arpowers** [comment]
In this case, these are form submissions. Why would you want them to be editable?

**Comment by ghost** [comment]
Why?
![Screenshot 2020-01-17 at 20 00 17](https://user-images.githubusercontent.com/2323952/72638585-06187380-3964-11ea-89a3-f52faeda1a36.png)
this is why i wont edit title post content  url etc..  or this is useless in start
