### ISSUE TITLE
At the end of blog posts, link to other blog posts to increase engagement

### ISSUE THREAD

**Issue by nodesocket** [fictionco/fiction#121]
Ghost does this, at the end of each blog post, it shows you another post to increase engagement to other posts on the blog. Can be randomized, or even statically defined.

> You may also enjoy...

![image](https://user-images.githubusercontent.com/523312/72863228-72adae00-3c95-11ea-9543-e52a2f9fd508.png)

**Comment by mohitsehgal** [comment]
When can we expect this?
