### ISSUE TITLE
Add additional author details to each blog post

### ISSUE THREAD

**Issue by nodesocket** [fictionco/fiction#122]
I'd like to add an additional few sentences to each blog post by a given user that supports html inside it. For example:

![image](https://user-images.githubusercontent.com/523312/72863453-40e91700-3c96-11ea-9772-35949b76f8c5.png)

That way you can write a few sentences about each author and have marketing outbound on each blog post.

**Comment by arpowers** [comment]
Some of these features are easily done via customization. How that is handled is as follows: 

If a component is loaded via setting: 

```js
// factor-settings
export default {
  blog: {
    postComponent: () => import('./theme-post-component.vue')
 }
}
```
Then all you need to do is copy the original component into your app, customize it as you like, and override the setting with your own:

```js
// factor-settings
export default {
  blog: {
    postComponent: () => import('./my-post-component.vue')
 }
}
```

**Comment by arpowers** [comment]
However, we DO need to make sure that things are appropriately "overrideable" with "Zeno theme" @finestpixels  is on top of that.
