### ISSUE TITLE
404 returns a 200 status code

### ISSUE THREAD

**Issue by nodesocket** [fictionco/fiction#128]
When navigating to a page that does not exists, the page body returns:

> 404 Error
> This page doesn't exist.

Yet the http response code is `200`. For SEO and best practice it should return a `404` http response code.

```
Request URL: https://elasticbyte.dev/does-not-exist
Request Method: GET
Status Code: 200 
Remote Address: 104.27.138.73:443
Referrer Policy: no-referrer-when-downgrade
```

**Comment by arpowers** [comment]
I don't think this is an issue, I'm not sure offhand how this would be solved since the Express server doesn't "know" if a page is 404 or not, that's handled by Vue Router.

**Comment by nodesocket** [comment]
It certainly is an issue. You want to be returning the right status codes, those are the language of http. How do you detect whether to display the text:

> 404 Error
> This page doesn't exist.

See: https://stackoverflow.com/questions/54218371/how-to-get-a-404-response-in-vue-router

**Comment by arpowers** [comment]
The response itself is not that important, if you want i can add: 
```html
<meta name=”robots” content=”noindex”>
```
to the HTML on pages where a 404 is thrown

**Comment by nodesocket** [comment]
Yup, probably a good idea to add that meta tag if returning a 404 status code is not possible.
