### ISSUE TITLE
Sitemap includes signin page. Sitemap.xml optimization

### ISSUE THREAD

**Issue by nodesocket** [fictionco/fiction#129]
Should the `sitemap.xml` include `/signin` page?

See: https://elasticbyte.dev/sitemap.xml

Also, I am by no means and SEO expert but other popular frameworks add additional attributes:

```
<lastmod>
<changefreq>
<priority>
```

See: https://www.sitemaps.org/protocol.html

 Does that make a difference? Take a look at a Ghost sitemap to see what they do:

https://blog.elasticbyte.net/sitemap.xml

**Comment by arpowers** [comment]
Signin page should be discoverable. I'll try and improve the ui, `lastmod` etc, aren't required if you aren't doing the work to tune the numbers.
