### ISSUE TITLE
Static assets in production mode are setting Cache-Control: max-age=0 response header

### ISSUE THREAD

**Issue by nodesocket** [fictionco/fiction#137]
Why when running in production `yarn factor serve` are all static assets such as `.js`, `.css`, `.svg`, `.png` setting a response header from Node.js of `Cache-Control: public, max-age=0`?

This poses a problem when using Cloudflare and trying to cache assets. `cf-cache-status` is always `EXPIRED` thus a roundtrip from Cloudflare to the origin always occurs.

I'd recommended not returning a`Cache-Control` header from Node.js for static assets and let Cloudflare handle it. Or else, set `max-age` to a reasonable value like 30 days in production only.

**Comment by arpowers** [comment]
@nodesocket which file and environment? The `maxAge`  should be set to 24 hours in production

**Comment by nodesocket** [comment]
Just running `yarn factor serve` and setting `FACTOR_URL`:

## CSS

```
curl -i http://127.0.0.1:3000/css/1-4fec65d4.css
HTTP/1.1 200 OK
X-Powered-By: Express
Accept-Ranges: bytes
Cache-Control: public, max-age=0
Last-Modified: Wed, 19 Feb 2020 05:26:43 GMT
ETag: W/"3e87-1705be9a238"
Content-Type: text/css; charset=UTF-8
Content-Length: 16007
Date: Wed, 19 Feb 2020 19:34:32 GMT
Connection: keep-alive
```

## JS

```
curl -i http://127.0.0.1:3000/js/1.4fec65d4.js
HTTP/1.1 200 OK
X-Powered-By: Express
Accept-Ranges: bytes
Cache-Control: public, max-age=0
Last-Modified: Wed, 19 Feb 2020 05:26:43 GMT
ETag: W/"6882-1705be9a238"
Content-Type: application/javascript; charset=UTF-8
Content-Length: 26754
Date: Wed, 19 Feb 2020 19:36:15 GMT
Connection: keep-alive
```

## SVG

```
curl -i http://127.0.0.1:3000/aws-5f8d9fa5.svg
HTTP/1.1 200 OK
X-Powered-By: Express
Accept-Ranges: bytes
Cache-Control: public, max-age=0
Last-Modified: Wed, 19 Feb 2020 05:26:43 GMT
ETag: W/"c31-1705be9a238"
Content-Type: image/svg+xml
Content-Length: 3121
Date: Wed, 19 Feb 2020 19:35:41 GMT
Connection: keep-alive
```
