### ISSUE TITLE
Multi-Tenancy Support?

### ISSUE THREAD

**Issue by st-schneider** [fictionco/fiction#142]
Does Factor support Multi-Tenancy? Couldn't find an answer on the page.

**Comment by arpowers** [comment]
Sure, it should/could. Not exactly sure what you mean but happy to discuss your use-case.

**Comment by st-schneider** [comment]
multiple sites/domains with the same visual content but for example different languages and some different style maybe administrated in one instance of factor.

**Comment by arpowers** [comment]
Yes! We have several sites sharing databases, and you could run several sites on the same server just using different ports. Shouldn't be a problem.

Might take is a bit to provide all the docs and examples. Happy to provide support here or on the forum which we will make live this week.

**Comment by arpowers** [comment]
We also have a "source" property on all posts which can be used to control what shows up where.

**Comment by st-schneider** [comment]
As a reference, good ol' wp https://wordpress.org/support/article/create-a-network/

**Comment by arpowers** [comment]
Ah yes, good ol multisite. So you'd like to spin up sites the same way?

There is a bit of work involved in allowing users to run sites, but it's possible.. Each would just get their own collection in MongoDB. Not sure how that would scale As of yet.

**Comment by st-schneider** [comment]
Yes, for example if you have example.com, example.de, example.co.uk and so on. And you want to admin it from one instance.
That is the main dealbreacker for most CMS headless or not.

**Comment by arpowers** [comment]
@bm-stschneider yes, i think this works already. You can specify the source app for any post you add to the system, we run https://factor.dev and https://fiction.com on the same DB.

**Comment by arpowers** [comment]
can we move this conversation to the Factor Forum? Its brand new and i want to test it a bit... 

https://factor.dev/forum

**Comment by st-schneider** [comment]
I actually don't want to sign up anywhere for a cms.
