### ISSUE TITLE
Factor forum markdown code not visible

### ISSUE THREAD

**Issue by samsour** [fictionco/fiction#143]
**Reason for this issue**
Hi, I was about to create a post in the new Forum and stumbled across a strange bug that made markdown code sections disappear/invisible. This does not happen in the edit mode.

**Steps to Reproduce**
[See this post](https://factor.dev/topic/5e56f4695a9997002c376502/how-to-set-custom-page-template-settings) or create a new forum post and add something in the markdown code brackets `.

Screenshots:

Edit mode:
![image](https://user-images.githubusercontent.com/37221148/75397880-50dcc200-58f8-11ea-8af4-91d75c63c7b0.png)

Forum post view:
![image](https://user-images.githubusercontent.com/37221148/75397926-79fd5280-58f8-11ea-86ed-b8cb09d85263.png)

**Comment by arpowers** [comment]
It is because you didn't add a "js" but it should still work I suppose. Will fix and improve.

Thanks!
