### ISSUE TITLE
Blog posts are not shown consistently

### ISSUE THREAD

**Issue by alighali85** [fictionco/fiction#150]
**Reason for this issue**
after creating and publishing some posts, I am not able all the time to see them.

**Steps to Reproduce**

1. sign in as an admin
2. create a post and publish it
3. go to the app and click on the blog tab
4. you will be redirected to the blog page
5. you will get No Posts, even thought you have published already some posts
6. repeat  the first 5 steps above, from the dashboard click on the app icon-name (top left)
7. click on `visit Site` you will see the posts (sometimes not)

**Comment by arpowers** [comment]
@alighali85 thanks, this sounds like a store/query issue. This is with the latest blog plugin? what theme and version are you using?

**Comment by arpowers** [comment]
@alighali85 did this get resolved in `1.4.10`? I believe it was a problem with the Zeno theme.
