### ISSUE TITLE
Can't remove avatar in Blog

### ISSUE THREAD

**Issue by siebevh** [fictionco/fiction#152]
**Reason for this issue**
I couldn't remove my selected avatar in a blog post
**Steps to Reproduce**
* Create A blog
* Add your avatar
* Save your blog
* Go To view
* Edit your blog post and delete your post
* Save your post
=> image will be back

<img width="1680" alt="Schermafbeelding 2563-03-12 om 19 58 30" src="https://user-images.githubusercontent.com/34541597/76557453-e00edb80-649b-11ea-8d74-ba22ec78a9f8.png">

**Comment by arpowers** [comment]
@siebevh thanks for the issue, it looks like you're using an older version (this bug was patched already)... did you run: 
```bash
npm upgrade
```

or
```bash
yarn upgrade
```

**Comment by siebevh** [comment]
@arpowers I just downloaded everything today, in which version of which package is this fixed? than i could check the version I have

**Comment by arpowers** [comment]
What version are you using of `@factor/core`? it should be on the CLI... latest version is `1.4.10`... The only way I can tell is the user icon was changed to circular on recent releases...

**Comment by siebevh** [comment]
strange I'm at "version": "1.4.10"

**Comment by arpowers** [comment]
ok i'll take another look then... might be a regression of some kind.
