### ISSUE TITLE
Database issue

### ISSUE THREAD

**Issue by mikeopatskyi** [fictionco/fiction#153]
When I have installed factorjs app in a DB i don't see user document, seems like user document has to be created automatically but it doesn't! I see posts document but nothing more.

**Comment by arpowers** [comment]
User document in the db?

**Comment by arpowers** [comment]
All documents are stored in a single collection "posts"... Can you clarify?

**Comment by mikeopatskyi** [comment]
> All documents are stored in a single collection "posts"... Can you clarify?

sorry, I meant user collection
