### ISSUE TITLE
Hiding / Deactivating any feature in Theme

### ISSUE THREAD

**Issue by mohitsehgal** [fictionco/fiction#158]
**Reason for this issue**
How can we disable any particular section, like Logos section in Zeno theme, I just dont want that. I removed its reference from navigation, How do I disable (not remove -- may need later) that for now?

**Steps to Reproduce**
Install any theme, let's say Zeno.
Try to customize

**Comment by arpowers** [comment]
Everything should be either:

- overrideable - by adding your own component in `factor-settings`
- setting enabled - where the theme author just needs to make sure it's set up

Finally, as a quick fix you can sometimes just hide w CSS. This is a last resort however.

In the case you mention, if you'd like it as a setting or it's not set for easy override. Contact the theme author or post an issue @finestpixels

**Comment by mohitsehgal** [comment]
Sure, will do that, for now, I am just customizing the .vue file.

**Comment by mohitsehgal** [comment]
I tried to comment "/pricing" route in index.ts, still it's not giving 404. Pricing Page is intact

**Comment by mohitsehgal** [comment]
index.ts

import { addFilter, setting, addContentRoutes } from "@factor/api"
import { Component } from "vue"

if (setting("headTags") != "") {
  addFilter({
    key: "addZenoFont",
    hook: "factor_head",
    callback: (_: []) => {
      return [..._, setting("headTags.font")]
    },
    priority: 200
  })
}

// CONTENT ROUTES

addContentRoutes({
  key: "zenoRoutes",
  routes: [
    {
      path: "/",
      component: setting("home.component"),
      meta: { nav: true }
    },
    {
      path: "/about",
      component: (): Promise<Component> => import("./v-about.vue"),
      meta: { nav: true }
    },
    {
      path: "/contact",
      component: (): Promise<Component> => import("./v-contact.vue"),
      meta: { nav: true }
    },
    // {
    //   path: "/pricing",
    //   component: (): Promise<Component> => import("./v-pricing.vue"),
    //   meta: { nav: true }
    // }
  ]
})
