### ISSUE TITLE
How to remove/disable existing routes for Zeno theme?

### ISSUE THREAD

**Issue by mohitsehgal** [fictionco/fiction#159]
**Reason for this issue**
I wanted to use Zeno theme for my new blog.
I wanted to remove /pricing route.
There is no way to removeContentRoute . I searched in the APIs also tried commenting /pricing route in index.ts file
**Steps to Reproduce**

**Comment by arpowers** [comment]
@finestpixels ?

**Comment by mohitsehgal** [comment]
We can do it using new `editContentRoute` API

```
editContentRoute({
  path: '/pricing',
  action: 'remove'
})

```
