### ISSUE TITLE
Plugin: Email List - No way to add style to input field of component.

### ISSUE THREAD

**Issue by mohitsehgal** [fictionco/fiction#160]
**Reason for this issue**
There is no way to add css or css class to input field in Factor's Email List Plugin.

**Steps to Reproduce**
This is what I got from https://github.com/fiction-com/factor/blob/development/%40plugins/plugin-email-list/email-list-form.vue
` <input
        v-model="email"
        type="email"
        :placeholder="setting('form.placeholder')"
        @keyup.enter="add()"
      />
      <factor-btn btn="primary" :loading="sending" @click="add()">
        <span v-formatted-text="setting('form.buttonText')" />
      </factor-btn>`

Please suggest.

**Comment by arpowers** [comment]
Target it with: 
```css
.add-email input { // css rules }
```

that work?

**Comment by mohitsehgal** [comment]
Yes worked
