### ISSUE TITLE
Custom Query on Posts and Use them in non-default route.

### ISSUE THREAD

**Issue by mohitsehgal** [fictionco/fiction#161]
**Reason for this issue**

I wanted to display the latest 10 posts on the home page of a factor app.
So, I checked the blog-index.vue in factor-blog-plugin, Where there are all posts are shown along with pagination, But I couldn't get how to do a custom query on specific post type?

What is the best way to create a posts-list widget with a given query and a given limit?

**Comment by mohitsehgal** [comment]
There can be usecase like. List All blog posts of a particular category / tag and sort them. Something on that terms.

**Comment by arpowers** [comment]
You can try to request a post list or post index: 
```js
import {requestPostIndex, requestPostList} from "@factor/post/request"
import { PostStatus } from "@factor/post/types"

const postIndex = await requestPostIndex({
    postType: "blog",
    tag,
    category,
    status: PostStatus.Published,
    sort: "-date",
    page,
    limit
  })

// postIndex has {posts, meta} 
// meta = information about the query

```
