### ISSUE TITLE
Blog Plugin: Permalink structure customization for SEO

### ISSUE THREAD

**Issue by mohitsehgal** [fictionco/fiction#162]
In the blog plugin, how can we customize the permalink structure, which is very important for the overall SEO of a content-based website.
Like we would like to have blog-posts in 1 category to have url like:
/cateegory1/perma-link-blog
and other having
/category2/perma-link-blog-2
and so on.
How can we do that?

**Comment by mohitsehgal** [comment]
How can we do it? 
Adding a custom filter?
Add additional field to the schema?

**Comment by arpowers** [comment]
Let's not post multiple questions in the same thread, remember it's about searchability...

**Comment by arpowers** [comment]
To add to the general `post` type that is shared by all posts in the system, you can use the `post-schema` filter.

something like: 

```js
import {addFilter} from '@factor/api'

addFilter({
  key: 'your-ref-key', 
  hook: 'post-schema',
  callback: schemaDef => {
 
    schemaDef.mySpecialCategory: { type: String, index: true }

    return schemaDef  
  }
})
```

**Comment by mohitsehgal** [comment]
@arpowers  Gotcha
Now how to get this `mySpecialCategory` in `addContentRoute` ?

**Comment by arpowers** [comment]
can you split this into it's own thread? People will find this thinking its about permalinks

**Comment by mohitsehgal** [comment]
Opened at https://github.com/fiction-com/factor/issues/165

**Comment by mohitsehgal** [comment]
Re-opened related ticket at https://github.com/fiction-com/factor/issues/168

**Comment by mohitsehgal** [comment]
> To add to the general `post` type that is shared by all posts in the system, you can use the `post-schema` filter.
> 
> something like:
> 
> ```js
> import {addFilter} from '@factor/api'
> 
> addFilter({
>   key: 'your-ref-key', 
>   hook: 'post-schema',
>   callback: schemaDef => {
>  
>     schemaDef.mySpecialCategory: { type: String, index: true }
> 
>     return schemaDef  
>   }
> })
> ```

This didn't worked

**Comment by mohitsehgal** [comment]
Here are the steps to do it:
1. Add custom field name `primaryCategory` in posts schema.
```
addFilter({
  key: 'blog',
  hook: 'post-schema',
  callback: schemaDef => {

    schemaDef.primaryCategory= { type: String, index: true }

    return schemaDef
  }
})
```

Key --> Post type
Hook --> It is standard, use as it is.
modify schemaDef according to your needs.

2. Add Input for new field in Admin Dashboard.
i) Add filter to attach a vue component for editing
pushToFilter({
```
  key: "blog",
  hook: "post-edit-components",
  item: {
    name: "AY Fields",
    component: setting("blog.categories.components.categoryDashboardEdit"),
  }
})
```
ii) Add that `categoryDashboardEdit` component to factor-settings.ts  like this

```
blog: {
categories:{
      indexRoute: "/topics",
      postRoute: '/topics',
      components:{
        category:(): Promise<Component> => import("./ay-blog/categories/category-wrap.vue"),
        categoryIndex:(): Promise<Component> => import("./ay-blog/categories/category-index.vue"),
        categorySingle:(): Promise<Component> => import("./ay-blog/categories/category-single.vue"),
        categoryDashboardEdit:(): Promise<Component> => import("./ay-blog/categories/category-edit-dashboard.vue"),
      }
    }
}
```

iii) Vue component for editing in dashboard
```
<template>
  <div class="edit-post-blog">

    <dashboard-input
    name="Primary Category"
      v-model="post.primaryCategory"
      input="factor-input-text"
      label="My Primary Category hereA"
    />
    <!-- More inputs -->
  </div>
</template>
<script>
  import { dashboardInput } from "@factor/dashboard"
  import {stored} from "@factor/api"
  export default {
    components:{
      dashboardInput
    },
    props: {
      postId: { type: String, required: true }
    },
    computed: {
      post() {
        return stored(this.postId) || {}
      }
    }
  }
</script>
```

3. Modify the Content Route for your post using `editContentRoute` in index.ts

```
editContentRoute({
  path: setting("blog.indexRoute") ?? "/",
  action:'edit',
  callback:routeDef=> {
    routeDef.children= [
      {
        path: "/",
        component: setting("blog.components.blogIndex"),
        meta: { index: true }
      },
      {
        path: `/:primaryCategory/:permalink`,
        component: setting("blog.components.blogSingle")
      }
    ]
    return routeDef;
  }

})
```


Full source code at 
https://github.com/mohitsehgal/factor-playground/blob/master/src/index.ts
