### ISSUE TITLE
Theme Alpha: Footer not at bottom

### ISSUE THREAD

**Issue by siebevh** [fictionco/fiction#163]
**Reason for this issue**
![Schermafbeelding 2563-03-17 om 20 30 43](https://user-images.githubusercontent.com/34541597/76894343-445fdf80-688e-11ea-86ad-e6403faf8f9b.png)
Footer not at the bottom of the page in theme alpha is this possible to always set it on the bottom of the page?
**Steps to Reproduce**

**Comment by arpowers** [comment]
Sticky is almost always a problem on mobile. I recommend setting a min-height to the content.

```css
min-height: 100vh;
```

**Comment by siebevh** [comment]
what would be the problem on mobile?

**Comment by arpowers** [comment]
`position: fixed;` has historically been janky on mobile.  If that's what you mean, in most cases with footers I'd just suggest that you make sure the content area  height is always tall enough to keep the footer at the bottom.

**Comment by siebevh** [comment]
No I don’t mean `position:fixed`, I think the theme should have standard styling on the footer to postion the footer always on the bottom, because I think I’m not the only one who will encounter this issue, if you understand me

**Comment by arpowers** [comment]
not totally, it seems like min-height would solve the problem you're asking about.

**Comment by siebevh** [comment]
It will be a solution but is not the best, because you will not see the footer when there is to little to display only a large blank space at the bottom

**Comment by arpowers** [comment]
Best would be just to provide an example site that has what you're suggesting.

**Comment by siebevh** [comment]
When you download the alpha theme and launch it, when you go to the login page on a large screen the footer will not be at the bottom of your page

**Comment by siebevh** [comment]
for example at https://underbelly.is/all-ears the footer will always be visible even when there is not enough content to cover a whole page

**Comment by arpowers** [comment]
@finestpixels ?

**Comment by raylopro** [comment]
This was fixed in the latest update @siebevh
