### ISSUE TITLE
How can we customize URL for Viewing Posts 

### ISSUE THREAD

**Issue by mohitsehgal** [fictionco/fiction#165]
**Reason for this issue**
How can we customize URL for Viewing Posts with custom fields like Primary Category?

I added primaryCategory in schema.
Now I want to customize URL for the post.
How can we do it?

**Comment by arpowers** [comment]
This can actually be done by just adding a route with a `:permalink` parameter and whatever else you'd like... 

Set up a route like this (untested)

```js

addContentRoute({
  path: "/whatever/:customParameter/:permalink
})
```

with that is should still pull the data automatically that associated with the permalink and add it to `post` in the store.

**Comment by mohitsehgal** [comment]
Please let me try and verify before closing the ticket. Humble request

**Comment by mohitsehgal** [comment]
I have tried this, this doesn't work
