### ISSUE TITLE
addPostEditComponent Isn't adding a box to post options

### ISSUE THREAD

**Issue by siebevh** [fictionco/fiction#166]
**Reason for this issue**
I want to extend the dashboard with custom input fields.
According to the documentation this could be done in the following way.
![Schermafbeelding 2563-03-18 om 18 44 10](https://user-images.githubusercontent.com/34541597/76990581-7afa3080-6948-11ea-8fdf-8ddfc1f4b117.png)
but when I look in this repo the @factor/api has no declaration of addPostEditComponent
![Schermafbeelding 2563-03-18 om 18 46 53](https://user-images.githubusercontent.com/34541597/76990816-dcba9a80-6948-11ea-9ddd-8b6905b4d5ee.png)

**Comment by arpowers** [comment]
I'll clarify this, you can find that function in `@factor/post`

```js
import {addPostEditComponent} from "@factor/post"
```

as a tip, you should keep a copy of the Factor repo on your computer, if you have a problem you can always look for the function in the project to see where the import should come from.

**Comment by siebevh** [comment]
I have changed it to "@factor/post" but does not see any new items on dashboard 
https://github.com/siebevh/eskapo

**Comment by arpowers** [comment]
Just ran it, saw this error: 

<img width="955" alt="Screen Shot 2020-03-18 at 3 54 58 PM" src="https://user-images.githubusercontent.com/308134/77011225-fe0f8c80-6930-11ea-8c69-4da50f0e93ea.png">

added this: 
```js
import { stored } from "@factor/api";
```

Now we have this: 
<img width="1268" alt="Screen Shot 2020-03-18 at 3 56 18 PM" src="https://user-images.githubusercontent.com/308134/77011246-0bc51200-6931-11ea-995d-80711fd50091.png">
