### ISSUE TITLE
Ducomentation not correct

### ISSUE THREAD

**Issue by siebevh** [fictionco/fiction#167]
**Reason for this issue**
![Schermafbeelding 2563-03-19 om 16 08 50](https://user-images.githubusercontent.com/34541597/77082221-0d0f4100-69fc-11ea-8eed-ea566061fcf0.png)
The documentation of Extending an Existing Schema is not correct, the addFilter function now has only one param.
How could I add a field to an existing schema?

**Comment by mohitsehgal** [comment]
I faced same issue

**Comment by arpowers** [comment]
this has been fixed
