### ISSUE TITLE
New version of factor is not running for existing project

### ISSUE THREAD

**Issue by mohitsehgal** [fictionco/fiction#169]
**Reason for this issue**

![image](https://user-images.githubusercontent.com/1757104/77093053-76a94280-6a30-11ea-962d-f4d31fdfed3e.png)

**Comment by siebevh** [comment]
you have to be on node version 12. at which version are you now?

**Comment by arpowers** [comment]
There an error somewhere?

**Comment by siebevh** [comment]
@arpowers I had the same no errors just loading for ever, I was on a wrong node version then

**Comment by arpowers** [comment]
Interesting, we should probably add a node version check

**Comment by mohitsehgal** [comment]
I am already running on the latest node, I overcame the problem by stashing all code, re-installing all extensions.
