### ISSUE TITLE
postLink doesn't returned permalink

### ISSUE THREAD

**Issue by siebevh** [fictionco/fiction#171]
**Reason for this issue**
When i add a factor-link with the postLink method, it will return to the index page of the type not to the detail page of the post
<factor-link :path="postLink(post._id)">
question => how to get to the detail page with a factorLink via postLink?
**Steps to Reproduce**
repo: https://github.com/siebevh/eskapo
run code and try to go to detail of boxes from the boxes page

**Comment by mohitsehgal** [comment]
I also have similar question
