### ISSUE TITLE
Changelog for releases?

### ISSUE THREAD

**Issue by andreialecu** [fictionco/fiction#172]
I wasn't able to find a changelog, I think it's important to provide one and link it prominently.

We're looking at factor vs gatsby for several projects, but the lack of a changelog is concerning.

**Comment by arpowers** [comment]
I understand your concern. We're still ramping up; I've told another user that we'll be starting changelogs w v1.6.

**Comment by arpowers** [comment]
@andreialecu 

https://github.com/fiction-com/factor/blob/development/CHANGELOG.md

Added these, we will be improving them and adding blog posts, etc... we are working on a dashboard and dev experience redesign, then docs (again) and then we should be running on full power.
