### ISSUE TITLE
Plugin Email List giving "Unknown custom element" error

### ISSUE THREAD

**Issue by dselcan2** [fictionco/fiction#175]
**Reason for this issue**
I wanted to start playing with the email list plugin, so I created a new endpoint and pointed it to a simple v-email.vue file which only contains the following three lines from the plugin docs:
<template>
  <factor-email-list list-id="default" />
</template>
upon loading the new endpoint i am greeted with a page with no content besides the header&footer and the following error in the dev tools.

vue.runtime.esm.js:620 [Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.
warn @ vue.runtime.esm.js:620
patch @ vue.runtime.esm.js:6487
Vue._update @ vue.runtime.esm.js:3939
updateComponent @ vue.runtime.esm.js:4060
get @ vue.runtime.esm.js:4473
Watcher @ vue.runtime.esm.js:4462
mountComponent @ vue.runtime.esm.js:4067
Vue.$mount @ vue.runtime.esm.js:8405
init @ vue.runtime.esm.js:3115
merged @ vue.runtime.esm.js:3298
hydrate @ vue.runtime.esm.js:6368
hydrate @ vue.runtime.esm.js:6401
hydrate @ vue.runtime.esm.js:6401
patch @ vue.runtime.esm.js:6483
Vue._update @ vue.runtime.esm.js:3939
updateComponent @ vue.runtime.esm.js:4060
get @ vue.runtime.esm.js:4473
Watcher @ vue.runtime.esm.js:4462
mountComponent @ vue.runtime.esm.js:4067
Vue.$mount @ vue.runtime.esm.js:8405
init @ vue.runtime.esm.js:3115
merged @ vue.runtime.esm.js:3298
hydrate @ vue.runtime.esm.js:6368
hydrate @ vue.runtime.esm.js:6401
patch @ vue.runtime.esm.js:6483
Vue._update @ vue.runtime.esm.js:3939
updateComponent @ vue.runtime.esm.js:4060
get @ vue.runtime.esm.js:4473
Watcher @ vue.runtime.esm.js:4462
mountComponent @ vue.runtime.esm.js:4067
Vue.$mount @ vue.runtime.esm.js:8405
init @ vue.runtime.esm.js:3115
hydrate @ vue.runtime.esm.js:6368
patchVnode @ vue.runtime.esm.js:6275
patch @ vue.runtime.esm.js:6472
Vue._update @ vue.runtime.esm.js:3942
updateComponent @ vue.runtime.esm.js:4060
get @ vue.runtime.esm.js:4473
run @ vue.runtime.esm.js:4548
flushSchedulerQueue @ vue.runtime.esm.js:4304
eval @ vue.runtime.esm.js:1979
flushCallbacks @ vue.runtime.esm.js:1905
Promise.then (async)
timerFunc @ vue.runtime.esm.js:1932
nextTick @ vue.runtime.esm.js:1989
queueWatcher @ vue.runtime.esm.js:4396
update @ vue.runtime.esm.js:4538
Vue.$forceUpdate @ vue.runtime.esm.js:3963
forceRender @ vue.runtime.esm.js:3641
eval @ vue.runtime.esm.js:3663
eval @ vue.runtime.esm.js:337
Promise.then (async)
resolveAsyncComponent @ vue.runtime.esm.js:3686
createComponent @ vue.runtime.esm.js:3197
_createElement @ vue.runtime.esm.js:3431
createElement @ vue.runtime.esm.js:3350
vm.$createElement @ vue.runtime.esm.js:3491
render @ app.ts:48
Vue._render @ vue.runtime.esm.js:3542
updateComponent @ vue.runtime.esm.js:4060
get @ vue.runtime.esm.js:4473
Watcher @ vue.runtime.esm.js:4462
mountComponent @ vue.runtime.esm.js:4067
Vue.$mount @ vue.runtime.esm.js:8405
eval @ entry-browser.ts:17
eval @ vue-router.esm.js:2084
eval @ vue-router.esm.js:2083
eval @ vue-router.esm.js:2198
step @ vue-router.esm.js:1882
step @ vue-router.esm.js:1889
step @ vue-router.esm.js:1889
runQueue @ vue-router.esm.js:1893
eval @ vue-router.esm.js:2193
step @ vue-router.esm.js:1882
eval @ vue-router.esm.js:1886
eval @ vue-router.esm.js:2178
eval @ vue-router.esm.js:1925
eval @ vue-router.esm.js:2001
Promise.then (async)
eval @ vue-router.esm.js:1948
eval @ vue-router.esm.js:1969
eval @ vue-router.esm.js:1969
flatMapComponents @ vue-router.esm.js:1968
eval @ vue-router.esm.js:1904
iterator @ vue-router.esm.js:2159
step @ vue-router.esm.js:1885
step @ vue-router.esm.js:1889
step @ vue-router.esm.js:1889
eval @ vue-router.esm.js:1886
eval @ vue-router.esm.js:2178
hookClientRouterBefore @ router.ts:39
eval @ router.ts:134
iterator @ vue-router.esm.js:2159
step @ vue-router.esm.js:1885
runQueue @ vue-router.esm.js:1893
confirmTransition @ vue-router.esm.js:2186
transitionTo @ vue-router.esm.js:2073
init @ vue-router.esm.js:2771
beforeCreate @ vue-router.esm.js:1236
invokeWithErrorHandling @ vue.runtime.esm.js:1853
callHook @ vue.runtime.esm.js:4213
Vue._init @ vue.runtime.esm.js:4994
Vue @ vue.runtime.esm.js:5075
createApp @ app.ts:40
async function (async)
createApp @ app.ts:29
startClient @ entry-browser.ts:7
eval @ entry-browser.ts:21
./node_modules/@factor/app/entry-browser.ts @ main.js:1195
__webpack_require__ @ main.js:769
fn @ main.js:130
eval @ client:2
0 @ main.js:14362
__webpack_require__ @ main.js:769
(anonymous) @ main.js:907
(anonymous) @ main.js:910
Show 12 more frames

vue.runtime.esm.js:620 [Vue warn]: Unknown custom element: <factor-email-list> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <VEmail> at src/v-email.vue
       <Content> at node_modules/@factor/theme-alpha/src/content.vue
         <Site> at node_modules/@factor/app/site.vue
           <Root>
![Untitled](https://user-images.githubusercontent.com/22999126/77762566-04d98600-703a-11ea-8c27-521298bb2980.png)

**Steps to Reproduce**

create new endpoint
link to vue file containing the three lines from the plugin email list doc.

**Comment by arpowers** [comment]
Ya that's called a hydration error and it usually just means you have something wrong in a Vue component. 

To use the email list plugin, all you should need to do is import the component and add it to your component. It handles the rest. 

Without seeing your actual code, I'm assuming you're doing something a bit incorrect.  There should be no need for server middleware, etc... the plugin handles all the data (that's the point)

**Comment by arpowers** [comment]
Here is an example of how to use this plugin (from how we are using it at Factor)

<img width="673" alt="Screen Shot 2020-03-27 at 10 04 59 AM" src="https://user-images.githubusercontent.com/308134/77775658-7ac9f700-7012-11ea-8e7f-e0f2da884ea6.png">

Here is the actual code: 

https://github.com/fiction-com/factor/blob/development/%40apps/factor/src/home/el-join.vue

**Comment by dselcan2** [comment]
I see, that example helped.
I missed that I needed to import the component in the script tag.
Thanks!
