### ISSUE TITLE
No clear way to manage User Roles.

### ISSUE THREAD

**Issue by stephenscaff** [fictionco/fiction#176]
**Reason for this issue**

Not seeing a method for changing / setting / updating a user's Roles in the Admin.

I'd imagine this capability would be a form select on the User's page in the dashboard, if viewing as admin. 

**Steps to Reproduce**
When I log in to dashboard as admin and visit a User's entry, no feature is available to manage their Role (form select with possible Roles as options).

Additionally, can you define a default level for new users - for example, all new user signups are Contributors?

Thanks Guys.

**Comment by arpowers** [comment]
This is implemented on the list users interface; see dropdown at the top...  

You're correct that we need to add this option on the edit account page for individual users. 

I'll leave this issue open until that is done. Thanks!

**Comment by stephenscaff** [comment]
First - thanks for the fast response. Very awesome.
Second - derps.... I see that now. My bad man. 

Been searching through the repo to uncover most the stuff I can't pull from the docs. Missed this one.

Is there a way to set a default signup level, like FACTOR_ADMINS in .env?
IE: FACTOR_CREATORS="carlosdanger@email.com,..."


Sidenote - I'm digging Factor. Nice work. Gonna commit to it for a thing I'm building right now, so might be bugging you some more (will join Slack Channel)

Docs could be bulked up a bit though. More than willing to contribute towards that once I finish building something useful?

**Comment by arpowers** [comment]
Glad to hear that Steve. 

First question, why would you need to systematically assign (using .env) vs just creating an admin and then promoting via dashboard?

**Comment by stephenscaff** [comment]
Yeah, fair enough. 

To provide a reduced admin experience - so Creators would only see the post type they can edit (and their profile).  

Background -  building a site/app for this design event that's now gone to an online format, with the end of days and all.

I'll have admins and users for the participating designers. 

They'll be able to go create a custom post and update images of their explorations for other authenticated users to comment on. (trying to figure that part out now).

Honestly, keeping designers as front-end users would probably be a better move. But, limited on time so adding features/capabilities in stages.

**Comment by arpowers** [comment]
I'll work with you to create what you need. Everything is possible, it's just about focus and time. Let me know if you run into additional issues.
