### ISSUE TITLE
[plugin/storage-google-cloud] Plugin requires setup despite all variables are present

### ISSUE THREAD

**Issue by yanchesky** [fictionco/fiction#177]
When launching app in console prints notification "setup needed". `GOOGLE_APPLICATION_CREDENTIALS` and `GOOGLE_CLOUD_STORAGE_BUCKET` are supplemented.

I dig in node_modules and found that first condition should be tested negative. When `!` is added  before, everything works fine. Otherwise, uploads are saved in DB.
![image](https://user-images.githubusercontent.com/37340314/78063857-249de080-7391-11ea-97c5-40b8f28aa170.png)

**Steps to Reproduce**
- Add google storage plugin to project
- put in .env `GOOGLE_APPLICATION_CREDENTIALS` or `GOOGLE_APPLICATION_CREDENTIALS_JSON` and `GOOGLE_CLOUD_STORAGE_BUCKET`
- run `yarn factor dev`

**Comment by arpowers** [comment]
Ya there might be a couple issues w this plugin as it's not been fully tested. Everything else is working ok?

**Comment by yanchesky** [comment]
Seems so. Adding and deleting works fine
