### ISSUE TITLE
LDAP login

### ISSUE THREAD

**Issue by gergogy** [fictionco/fiction#178]
**Reason for this issue**
Hello,

**Firstly, this project just looks amazing.**

I'd like to make my project based on this, but there is one thing that I don't know...
Can I implement LDAP based login somehow? (package that I'd use: https://www.npmjs.com/package/ldapjs)
Is there any way to implement this?

The imaginary login process (Sorry if I miss some steps):

1. User navigates to login page
2. Give the credentials that used in LDAP
3. LDAP bind request fired, with given creds
4. If LDAP bind was successfully
    - if not exist user created (blank pwd maybe?) with Member permission level, no need for email verification (how can I skip the email part?)
   - user populate
   - redirected to dashboard (profile page) 
5. Otherwise wrong email/password given error thrown

**Comment by arpowers** [comment]
Thanks @gergogy .. first a question. 

what's the use case for LDAP specifically? 

I can tell you that Factor is designed for extension from the start, so everything we've come across "can" be implemented with an extension or directly inside an app. It's just about focus, time,  and who implements it.

**Comment by arpowers** [comment]
The core authentication strategy is based around the awesomely simple JWT approach, this can easily work with other ways of doing auth like OAuth and I assume LDAP,  but again i'd need to know the use case to recommend an approach

**Comment by gergogy** [comment]
Yes, JWT awesome, I don't want to replace the whole authentication and security things, just the login.
The cause why I need this is simple, customer need this... They had full bunch of applications that using LDAP already. So they want to integrate this to that ecosystem.
So, as I wrote earlier, I don't want to fully replace JWT, just the login/registration (To be honest, registration will be disabled, no need for that).

**Comment by gergogy** [comment]
Here is a tutorial from IBM: https://developer.ibm.com/technologies/node-js/tutorials/se-use-ldap-authentication-authorization-nodejs-cloud-application/ (_Logging on to an LDAP server_ section), and example code: https://github.com/qbzzt/bluemix/blob/master/security/201802/login-using-ldap/app.js

It's not a big thing, I think... just don't want to mess up the code.

Thanks for your time!

**Comment by arpowers** [comment]
ok thanks; i can tell from quickly checking the tutorial that this is a pretty standard middleware oriented plugin that is needed. However, it's going to be very hard to implement it myself in the short term. 

What I can do is clean up the docs and try and make it easy for you to knock it out. Does that work for you?

**Comment by gergogy** [comment]
Yeah, if you can do that I think that would be enough.
If I get stuck I'll write... :)

Thanks in advance!
