### ISSUE TITLE
404 Http error when viewing newly-created `work`/`portfolio` (theme dependent)

### ISSUE THREAD

**Issue by igokul1973** [fictionco/fiction#179]
**Reason for this issue**
Upon addition of new "work" or "portfolio" (`work` in `Alpha`, `portfolio` in `Ultra`, I did not check other themes) in the dashboard the link to view it does not work, issuing 404 HTTP error.

**Steps to Reproduce**
1. Install, for example, `Alpha` theme. It has the `work` type.
2. Go to dashboard, try to Add New Work.
3. After clicking Update button, click View button.
4. The system takes you to the `http://localhost:3000/working` without any permalink after the 'working' URI part - 404 HTTP error as a result.
5. The same happens if one goes to `http://localhost:3000/work` and tries to click the newly-created work post.

The problem lies in missing `customPermalink: true` in the PostTypeConfig argument in the theme's addPostType function call (`@factor/theme-alpha/src/index.ts: 18`):
```
addPostType({
    postType: "work",
    baseRoute,
    icon: require("./img/dashicon-work.svg"),
    nameIndex: "Work",
    nameSingle: "Work Post",
    namePlural: "Work Posts",
    // customPermalink: true, <-- THIS IS MISSING!!!
    templateSettings: setting("work.templateSettings")
});
```

Please fix it and update the theme or explain/document if it was done on purpose...

Also, it if it is possible to extend the type (just like it is possible to extend the scheme, according to the documentation), please document it.

**Comment by arpowers** [comment]
@finestpixels can you take a look at this one?

**Comment by raylopro** [comment]
This has been fixed for both Alpha and Ultra theme in recent versions (1.5.20)
