### ISSUE TITLE
Blog Plugin: Search page

### ISSUE THREAD

**Issue by mohitsehgal** [fictionco/fiction#181]
Blog Plugin is not having a search page or no live search page on the blog. This is very important feature. Please guide towards it or add enhancement in blog plugin.

**Comment by arpowers** [comment]
The standard index request  `requestPostIndex` already supports a search parameter. Usually plugins will support this via a route query variable or path parameter (/path/:search)...

I've added support to the [standard factor blog](https://factor.dev/plugin/standard-blog) plugin  and you'll see that in the next release.  I can also maybe add a component for searching the blog, but you'll be able to do the same with `blog?search=mysearchquery`.

**Comment by mohitsehgal** [comment]
Ok thanks I will check
