### ISSUE TITLE
Blog Plugin : Comments

### ISSUE THREAD

**Issue by mohitsehgal** [fictionco/fiction#182]
In any CMS or blogging/page system. There has to be comments section, so that blog readers can leave a comment or carry out discussion. If there is no interaction with people then that would be very tough to adapt Factor as a primary blog platform or any developer adopting it.

Please guide to develop this feature quickly or add it in the official plugin.

**Comment by arpowers** [comment]
Comments plugin is coming. We are working on docs, then extensions
