### ISSUE TITLE
Populate fields on fetch

### ISSUE THREAD

**Issue by mohitsehgal** [fictionco/fiction#184]
I created a field called primaryCategory and added it to schema using 
```

addFilter({
  key: 'blog',
  hook: 'post-schema',
  callback: schemaDef => {
    schemaDef.primaryCategory = { type: objectIdType(), ref: "category", index: true }
    schemaDef.comments = [];
    return schemaDef
  }

})

pushToFilter({
  key: "primaryCategory",
  hook: "post-populated-fields",
  item: { field: "primaryCategory", depth: 20 }
})
```
I added, dashboard-edit component. It was getting saved in MongoDB.

Now when I fetch the post. I am not able to get whole category Object.

Do I need to do something extra?

**Comment by arpowers** [comment]
ok, what are you using to query the DB?

**Comment by arpowers** [comment]
If you are using a standard query request which accommodates population on its own (`requestPostSingle`)..  

Then you'll want to make sure that the posts that are being referenced actually exist with a `postType` of `category` in this case.  With that, it should be working. 

If not, i'd need to see more code to understand what's happening.

**Comment by mohitsehgal** [comment]
I am trying to get it on post-single page. Where Post is retrieved in stored('post'), along with other populated fields.
