### ISSUE TITLE
Plugin Suggestion: Notifications OneSignal

### ISSUE THREAD

**Issue by mohitsehgal** [fictionco/fiction#187]
Today most bloggers want to push content on Push Notifications on mobile devices and browsers.

Top service is OneSignal.
I wonder if community can plan a plugin to easily integrate OneSignal. That would be great.

**Comment by arpowers** [comment]
Push notifications are a bag of worms and there are no real universal standards that make it straight forward to integrate directly.  
That said, someone could easily to it with a plugin.
