### ISSUE TITLE
Limit Access to User Role - `Creator`

### ISSUE THREAD

**Issue by mohitsehgal** [fictionco/fiction#195]
![image](https://user-images.githubusercontent.com/1757104/79248992-3ce62300-7e9a-11ea-84af-16780eff52f4.png)

I had installed contact form, email lists, and work posts plugins.
We dont want normal users with role creators to access to Contact form submissions or email lists submissions.

How can we do that?

**Comment by arpowers** [comment]
This can be fixed, let me take a look in next couple days.

**Comment by mohitsehgal** [comment]
ok will be waiting
