### ISSUE TITLE
Access Level Bug for custom post type

### ISSUE THREAD

**Issue by mohitsehgal** [fictionco/fiction#196]
I added custom post type successfully and added  {accessLevel: 20} in `addPostType`. 
Then I signed up with new user. Verified its email. 
**Case 1**
Result - I was not able to see my custom post type in dashboard. ( New user had accessLevel 20 and role creator)

**Case 2**
I changed the accessLevel of the user from MongoDB to 50, and logged out and again logged in
Result - I was not able to see my custom post type in dashboard

**Case 3**
I changed the accessLevel of this user from MongoDB to 100, and logged out and again logged in.
Result - I was able to see my custom post type in the dashboard along with several others.

**What did I conclude?**
accessLevel parameter is not getting used in the code to determine which post types are shown on the dashboard. Instead, it is hardcoded to 100.

Revision
@factor/dashboard/menu.ts Line 73
https://github.com/fiction-com/factor/blob/cc86667c0143dfe0f89c5a569762ab9e7c984e64/%40factor/dashboard/menu.ts#L73
Hardcoded `accessLevel:100` for the dashboard menu.

**Comment by arpowers** [comment]
@mohitsehgal this should all be fixed, reference new [docs](https://factor.dev/docs)

**Comment by mohitsehgal** [comment]
Hi, I didnt got it in new docs either. Please give link of the page.

**Comment by mohitsehgal** [comment]
@arpowers
