### ISSUE TITLE
Bug Ultra theme

### ISSUE THREAD

**Issue by gersirami** [fictionco/fiction#197]
Hello,
I noticed in the Ultra theme, when you go to the news or portfolio posts, the menu doesn't work at all.

**Comment by mohitsehgal** [comment]
Yes I experienced same issue

**Comment by arpowers** [comment]
@finestpixels look into this please.

**Comment by gersirami** [comment]
I solved it by putting a "/" before every #path. Don't know if it's the best solution, but it works.

**Comment by raylopro** [comment]
Hi guys, a forward-slash "/" is the right way of adding these anchor links. Active nav items weren't working when adding a forward-slash to links before but should be fixed on next theme update.
