### ISSUE TITLE
Deployment of backend with PM2

### ISSUE THREAD

**Issue by mohitsehgal** [fictionco/fiction#198]
I was trying to deploy a Factor App to Ubuntu Server. 

Steps:
1. Installed Node, NPM, Mongodb, NGINX, PM2
2. Cloned the repo, `npm install`
3. Build it for production, `npx factor build`
4. When I do `npx factor serve`
It will launch the factor app till I am logged in from my system to ubuntu server.

I wanted to use standard node process manager like `forever` and `pm2` but I am not able to find  correct index script for node.

I tried with
src/index
.factor/loader-app.ts

It seems that file is generated on the go when we do `npx factor serve`
But they are lost as soon as I close the terminal window.

What can we do ?

**Comment by arpowers** [comment]
That should work fine, you just want to run the cli from a script right?  It is possible to run the cli as a script instead of via terminal, but usually that’s not needed.

The loader app file is not meant to run stand alone.

**Comment by arpowers** [comment]
As for a script, try this: 

`./node_modules/.bin/factor` which is the CLI executable. Let me know how it goes.

**Comment by mohitsehgal** [comment]
How to do that please Guide

**Comment by arpowers** [comment]
This should work in a similar way to the way nuxt works... they have a custom CLI, similar commands: 

https://github.com/nuxt/nuxt.js/issues/1541

**Comment by mohitsehgal** [comment]
Thanks @arpowers 
For those hitting the same issue, here is the command
`pm2 start ./node_modules/.bin/factor -i max`

**Comment by bnfan** [comment]
> Thanks @arpowers
> For those hitting the same issue, here is the command
> `pm2 start ./node_modules/.bin/factor -i max`

I create a script which runs `npx factor serve`, then use pm2 to start it, it works well so far.

**Comment by loicy** [comment]
Hi @bnfan !

Can you give me the script or explain to me plz ?

Thx !

**Comment by bnfan** [comment]
> Hi @bnfan !
> 
> Can you give me the script or explain to me plz ?
> 
> Thx !

Sure, it's very simple:

1.create a script, e.g. run.sh
2.In the script run the `npx factor sever`

```
#bash

npx factor server
```

3.Use pm2 to run it:

`pm2 start ./run.sh`

**Comment by loicy** [comment]
Hi @bnfan 

Working, thx !
