### ISSUE TITLE
Extend initial new Vue call

### ISSUE THREAD

**Issue by LoganArnett** [fictionco/fiction#199]
**Reason for this issue**
I am trying to use `Vuetify` in my Factor app and I am unclear on how I would include it in my app. I tried to extend on a few of the hooks but I have been unsuccessful so far. Has anyone tried doing this?

**Steps to Reproduce**
Try to install Vuetify in a Factor app

**Comment by mohitsehgal** [comment]
do the steps in index.ts @LoganArnett

**Comment by LoganArnett** [comment]
@mohitsehgal that is what I have been attempting but no matter the install option I use I continue to get errors on render with missing components

**Comment by arpowers** [comment]
@LoganArnett im working on a revamp of the docs which should be live this weekend. I can write an integration guide for this. 

What are the errors you’re getting?

**Comment by LoganArnett** [comment]
Currently I am getting this error:
![image](https://user-images.githubusercontent.com/8780547/79892727-f3816080-83d0-11ea-850b-66dc37850491.png)

I may also be configuring it incorrectly in the index. This is my first attempt at Factor and I am newer to Vue as well so I was just trying it out.

**Comment by LoganArnett** [comment]
Definitely curious to see how to integrate external pieces like this. I assume there is no way to use the Vue CLI since it is extracted behind the factor commands?

**Comment by arpowers** [comment]
Ah ok, so the `v-app` issue sounds like you aren't importing and adding it to the component: 

```js
import {vApp} from 'whatever'
export default {
components: {vApp}
}
```

That's just a guess, but basically Vue is saying it doesn't know what `v-app` is.

As for Vue CLI, ya that's a general scaffolding tool. So eventually we could make a Vue CLI plugin that scaffolds Factor apps. 

Factor kinda wraps up a lot of the CLI stuff and takes it out of user land. Like Webpack config and so on.. The goal with Factor is to simplify and get all the boilerplate coding out of your life. 

Look at docs next week you'll see a 1000x improvement.

**Comment by LoganArnett** [comment]
Yea, from the docs it looks like Vuetify is supposed to be integrated into the Vue instance and then the components are available but I will try importing like above
