### ISSUE TITLE
Short guide to get ready for theme and plugin development in new docs

### ISSUE THREAD

**Issue by IamSAB** [fictionco/fiction#200]
As you are currently writing new docs, I would be glad, if you could add a section with a guide, how to do the setup for theme and plugin development. Recommended editor, extensions, dependencies, folder structure, how to use yarn workspaces, factor cli.

---
I tried to use yarn workspace to run a plugin in a factor app, but could not get it working.  I tried this:
The folder structure

```
/workspace
    package.json
    /app
    /plugin
```
package.json
```json
{
  "private": true,
  "workspaces": [
    "app",
    "plugin"
  ]
}
```
Create factor app
```
cd /workspace/app
npx create-factor-app
```

Add /plugin/package.json wtih content
```json
{
    "name": "plugin",
    "factor": {
        "load": {
            "app": "index",
            "server": "server"
        },
        "extend": "plugin",
    }
}
```

Then i add "plugin"to the dependencies of the factor app, then I run 
```
yarn workspace app factor dev
```

The the server starts, it seems, the plugin gets loaded, but when I add a post type in the plugin, it will no appear on the dashboard:
```typescript
import { addPostType } from "@factor/api"
addPostType({
  postType: "plugin",
  baseRoute: '/add',
  nameIndex: "Plugin",
  nameSingle: "Item",
  namePlural: "Items",
  addSitemap: true
})
```
However, if I add it to directly to the factor app, it will show up in the dashboard. In the plugin and the app I add the post to the index.ts. Apparently, I am doing something wrong.

**Comment by arpowers** [comment]
Good idea with the yarn workspaces, i'll add that somewhere.. 

As for docs, you can see here that they will be pretty comprehensive: 

https://gist.github.com/arpowers/a9d91603a9ac02bb833659d51a6676fa

Checked boxes are what I've written so far.
