### ISSUE TITLE
Suggestion: Expose API methods to template

### ISSUE THREAD

**Issue by asvae** [fictionco/fiction#209]
## Reason
Sometimes you may want to call api methods directly from template. But there is no way to.

I.e. to open chat you would have to declare method.
```vue
<template>
  <button @click="openChat()">Open Chat</button>
</template>

<script>
import { emitEvent } from '@factor/api'

export default {
  methods: {
    openChat () {
      emitEvent("open-chat")
    }
  }
}
</script>
```

Be this implemented - the code would look like this:
```vue
<template>
  <button @click="$fa.emitEvent('open-chat')">Open Chat</button>
</template>
```

Which is way less code.

## Implementation
Something like this should work:

```ts
import * as factor from '@factor/api'

export const FactorPlugin = {
  install (vue: Vue) {
    Vue.prototype.$fa = factor
  },
}

// Not super sure that exact code would work. Probably something similar.
declare module 'vue/types/vue' {
  interface Vue {
    $fa: factor
  }
}
```

- [ ] Implement as Vue plugin
- [ ] ensure TS declarations work properly

## Concerns and details
* No treeshaking. All methods will be added to package.
* Intended for component/template usage (imports should be used in other places). But could be misused with `(new Vue()).$fa`.

**Comment by arpowers** [comment]
This is bad practice. Globals should be avoided at all costs; we tried this in the early days. 

To call from a template simply: 

```js
import {whatever} from "@factor/api"
export default {
methods: {whatever}
}
```
