### ISSUE TITLE
[Help] Client side rendered components (dep of window or something else)

### ISSUE THREAD

**Issue by gergogy** [fictionco/fiction#210]
**Reason for this issue**
I would like to use https://github.com/RobinCK/vue-gallery in my project for a gallery.

How can I implement something like mentioned in Readme (Nuxt like approach)?
If I missed something in the docs or code sorry. (I checked https://factor.dev/docs/main-files, but its unclear for me, I think there is a caveat. Under "Environmentally Specific Main Files" "If you want to load index.js in both the app and server, but only load server.js in the server environment then you can do this" this is the first sentence after the first example. However the last says: "From there you can extrapolate to loading any number of main files based on environments")

I want to use this lib in a component not a page/view.

I'd be glad if you send me an example "app".

Thanks!

**Comment by arpowers** [comment]
Typically, you'd use the main file to add routes along with their component (using `addRoutes`). Then you should have no problem adding your plugin inside the component. That help?

**Comment by gergogy** [comment]
No, I don't think so.
I added this content route earlier:
`
addContentRoute({ path: "/kepek",  component: () => import("./views/kepek.vue") })
`

I want to use the lib in a component what is imported in `kepek.vue`.

**Comment by arpowers** [comment]
Components can import other components, once you've created a route everything is just standard `vue` development.

**Comment by gergogy** [comment]
Okay, I think its a little misunderstanding here.
I know this is simple `vue` dev after that, BUT this component using `window`, which is not present on server side, so its throws me an error. Nuxt approach is that we can define client side only plugins/components (or other methods like no-ssr tag). I hope this will clarifies things.

**Comment by gergogy** [comment]
Sorry I forgot to add errors:
![image](https://user-images.githubusercontent.com/21192274/81723607-5ff8f800-9483-11ea-9ade-38f5de46837b.png)
Or if its loaded somehow (WTF?!), typical hydration error:
![image](https://user-images.githubusercontent.com/21192274/81723738-98003b00-9483-11ea-992f-1b54f22e8073.png)

**Comment by arpowers** [comment]
ah, ya.. you gotta say that lol...  This is done here: 
https://github.com/fiction-com/factor/blob/development/@factor/post/view/posts-edit.vue#L55

We just bring in the `vue-client-only` component and wrap the date picker (which has the same problem) with it... 

I'll mention that this is bad practice by the plugin authors.

**Comment by arpowers** [comment]
```html
<template>
<div>
  <vue-client-only><my-fancy-component /></vue-client-only>
  </div> 
</template>
<script>
export default {
  components: { 
    vueClientOnly: () => import("vue-client-only.vue"), 
    myFancyComponent: () => import("fancy.vue"),
  }
}
</script>
```

**Comment by gergogy** [comment]
Oh, I missed that, but I lookup for everywhere. Its not so bad... just like `no-ssr`. Thanks

**Comment by arpowers** [comment]
Ya we considered adding this to the core, but decided that there was no reason/benefit to that. Just bring in whatever `no-ssr` component you want ...
