### ISSUE TITLE
Cannot find module 'fs-extra'

### ISSUE THREAD

**Issue by jebalert** [fictionco/fiction#216]
**Reason for this issue**
First factor project, results in error. 
**Steps to Reproduce**
`npx factor dev`

**Comment by arpowers** [comment]
Did you run `npm install`? That's a standard Node module, should be installed.

**Comment by jebalert** [comment]
Yes, npm is installed.

Also note, npm found 2 low vulnerabilities 

┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ yargs-parser                                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=13.1.2 <14.0.0 || >=15.0.1 <16.0.0 || >=18.1.2             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @factor/core                                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @factor/core > @factor/loader > gravatar > yargs >           │
│               │ yargs-parser                                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1500                            │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ yargs-parser                                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=13.1.2 <14.0.0 || >=15.0.1 <16.0.0 || >=18.1.2             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @factor/core                                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @factor/core > @factor/ui > gravatar > yargs > yargs-parser  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1500

**Comment by arpowers** [comment]
Are you trying any imports or anything custom? It's possible to have this issue if you import `fs-extra` in the browser environment.

(I'll upgrade the packages, thanks)

**Comment by jebalert** [comment]
fysa, turns outs fs-extra is not included in npm install. I even went and reinstalled npm. 

The solution was:
`npm install fs-extra`

**Comment by arpowers** [comment]
@jebalert use yarn if you want to avoid these types of issues, NPM is a lot more fragile when it comes to package management for some reason.
