### ISSUE TITLE
Add babel-loader for IE/Firefox compatibility

### ISSUE THREAD

**Issue by gergogy** [fictionco/fiction#218]
**Reason for this issue**
Hi, I have compatibility issues with Firefox and MS Edge, the webpack output is not compatible, (ie: trailing commas in object, Promise, etc.). How can I add a babel loader for the project?
It has issues on server side because of it. I tried to push a default loader, in `'webpack-loaders'` hook:

`loaders.push({ 
      test: /\.?js$/,  
      exclude: /(node_modules|bower_components)/,  
      use: { 
        loader: 'babel-loader',  
        options: {  
          presets: ['@babel/preset-env']  
        }  
      }  
    })`

Can you help me?
**Steps to Reproduce**

**Comment by arpowers** [comment]
that's all handled by TypeScript which is set to target es2018. Doesn't that work in Firefox?

**Comment by gergogy** [comment]
Unfotunately no.

Az iPhone-omról küldve

**Comment by arpowers** [comment]
Which versions are we talking about?

**Comment by gergogy** [comment]
Not the latest version of edge (webkit based). Currently Im not in front of my computer, but this versions are reported: “ Windows 10 Pro (x64) és Windows 2012R2  alatt a legújabb Firefox” Windows 10 pro and Windows server with latest Firefox.

Az iPhone-omról küldve
