### ISSUE TITLE
Weird terminal output on windows

### ISSUE THREAD

**Issue by YerkoPalma** [fictionco/fiction#223]
**Reason for this issue**

There is some weird encoding with create-factor-app see this
![image](https://user-images.githubusercontent.com/5105812/87864515-3d79d400-c937-11ea-953d-9eee73f45cb6.png)

**Steps to Reproduce**
Well I just ran create-factor-app. I'm under windows 10, using Hyper with git-bash. Other modules doen't seems to have this issue.

**Comment by gustavobretas** [comment]
It is something with your git-bash theme, I use with PowerShell and my theme can handle all those special characters.

**Comment by FridayCandour** [comment]
> It is something with your git-bash theme, I use with PowerShell and my theme can handle all those special characters.

Please I can't Install it, do you have any stand alone option
