### ISSUE TITLE
Any chance you can loosen the requirement of signing up?

### ISSUE THREAD

**Issue by omarryhan** [fictionco/fiction#226]
**Reason for this issue**

Right now in order to view

1. the docs
2. available plugins
3. available themes

you are required to sign up first. I imagine that most people would want to at least glance at the docs before signing up. I'm confused about this requirement, especially that this project is open source which means that you can more or less read the info you need in the repo.

**Comment by nonissue** [comment]
I agree wholeheartedly. When I saw that themes, plugins, and even **documentation** (this boggles the mind) are walled off without signing up, I immediately left the site, and my first impression of the whole project is incredibly negative.

**Comment by arpowers** [comment]
@nonissue we've done this for two reasons. Primarily because we trying to reduce support requests from "casual" Users. Second, we are going to be upgrading to Vue3 and Vite in a few months; and reorganizing things as a headless CMS for easier public usage.
