### ISSUE TITLE
Deploying factor app to VPS

### ISSUE THREAD

**Issue by omortikweb** [fictionco/fiction#231]
For deploying factor app to vps, i followed the documentation where after upload the code, command call 
`npx factor build`
![npxx](https://user-images.githubusercontent.com/70368623/91800535-f3308600-ec4a-11ea-8234-b65c7e053f62.png)

here, i follow this step:
![Screenshot_2](https://user-images.githubusercontent.com/70368623/91800643-2f63e680-ec4b-11ea-92c0-0d27092d9a95.png)

**Comment by arpowers** [comment]
Haven't seen that one before, is it recognizing the `factor` cli command?

**Comment by omortikweb** [comment]
this problem was solved by deleting node_modules and again run `npm install` .
But after that, when ran `npx factor serve`
![Screenshot_3](https://user-images.githubusercontent.com/70368623/91964726-54328980-ed31-11ea-9c47-e5ed29bb9e7d.png)

 Not generate production mode. Why generate `http://localhost:3000` this url?

**Comment by abishekrsrikaanth** [comment]
Have the same issue, can't deploy to anything other than heroku. I was thinking of deploying to Vercel or Netlify and it just stops at that.
