### ISSUE TITLE
How to deploy factor to Vercel or Netlify?

### ISSUE THREAD

**Issue by abishekrsrikaanth** [fictionco/fiction#238]
It would be great if there are docs on how to setup the app on Vercel or Netlify

**Comment by abishekrsrikaanth** [comment]
@arpowers any updates on this?

**Comment by arpowers** [comment]
@abishekrsrikaanth are you planning on using those services as static site hosts?

**Comment by abishekrsrikaanth** [comment]
@arpowers, want to be able to deploy the site similar to hosting on heroku. Vercel does support server based hosting unlike netlify

**Comment by arpowers** [comment]
In the next version of Factor, we plan on supporting static sites.  For Factor 1.x you'll need to back things up with a Node server to handle your SSR.

Give me a few weeks and I can demo 2.0 :P

**Comment by abishekrsrikaanth** [comment]
Sounds good, Is there any way you can suggest to make SSR work with vercel similar to heroku. Trying to figure out where that whole heroku thing is tied up to make it work just with heroku for Production deployment.
