### ISSUE TITLE
checkbox not working as expect

### ISSUE THREAD

**Issue by ash0080** [fictionco/fiction#240]
**Reason for this issue**
Cannot save properly or even generate fields.

···
 templateSettings() {
    return [
      {
        input: "checkbox",
        label: "Show In Home",
        description: "Show it in homepage",
        _id: "inHome",
        _default: false,
      },
···

v1.8.26

**Comment by ash0080** [comment]
But I think the best way to do is to rewrite all UI components with v-model, 
[ref](https://vuejs.org/v2/guide/components-custom-events.html?#Customizing-Component-v-model)

**Comment by arpowers** [comment]
The pattern that is in place is related to wrapping, v-model doesn't work as well as you need to use watchers. 

However, if it's not working as expected, I'm happy to accept your PR. What was happening that was unexpected?

**Comment by ash0080** [comment]
> The pattern that is in place is related to wrapping, v-model doesn't work as well as you need to use watchers.
> 
> However, if it's not working as expected, I'm happy to accept your PR. What was happening that was unexpected?

Can‘t save or generate data field, or trigger event
