### ISSUE TITLE
Vue formulate for form ui

### ISSUE THREAD

**Issue by IamSAB** [fictionco/fiction#252]
I heard you are working on a new version of factor. I recently became friend with https://vueformulate.com/ which could be well suited for factor's form ui. It actually does the same but has more features, has a tough-out architecture and is very flexible.
It also support form generation from a javascript object or even json which would serve well for the template settings.

Why maintain your own form ui when there's one which could do the job better?

**Comment by arpowers** [comment]
Cool that's always been in the intention; to be extension first. V2 will take a different perspective on a few things; lets review in January.
