### ISSUE TITLE
lodash-es@^4.17.15 updates to 4.17.20 which results in ERR_REQUIRE_ESM

### ISSUE THREAD

**Issue by bppdddqqqq** [fictionco/fiction#257]
**Reason for this issue**

4.17.20 of lodash-es introduced a new setting set in package.json which results into an error for latest Node 12 and 14 runtimes. The error is ERR_REQUIRE_ESM.

**Steps to Reproduce**

Install the package without a lockfile

**Mitigation**

Set a resolution for lodash-es for 4.17.15

**Comment by voondo** [comment]
FYI a workaround is to add this in your `package.json`:
```
  "resolutions": {
    "lodash": "4.17.15",
    "lodash-es": "4.17.15"
  },
```

**Comment by dhruvsaxena1998** [comment]
> FYI a workaround is to add this in your `package.json`:
> 
> ```
>   "resolutions": {
>     "lodash": "4.17.15",
>     "lodash-es": "4.17.15"
>   },
> ```

Just tried, not working on windows

**Comment by Saunved** [comment]
Don't forget to run ```yarn``` or ```npm install``` after making this change!

**Comment by abishekrsrikaanth** [comment]
I have this same issue on v1.8.30
