### ISSUE TITLE
Open Source Software's docs should be open source too

### ISSUE THREAD

**Issue by cy2201** [fictionco/fiction#273]
I was interested in Factor. It looks good so I wanted to see the docs before I decide to develope with it. But why I need an account to see the docs? Factor is open source. Even it wasn't open source, I think the docs should be readable by everyone.

Offtopic: The "We're hiring" link in the footer is broken.

**Comment by arpowers** [comment]
The current version is in an archived state as we have been upgrading to newer breaking tech like Vite/Vue3, Postgres, etc.. The newer version is already in production for Darwin (https://www.darwin.so) and we are working on that launch before we formally begin development on the next public version of Factor.
