### ISSUE TITLE
Is there an upgrade guide for v1.8 to v3.x

### ISSUE THREAD

**Issue by abishekrsrikaanth** [fictionco/fiction#282]
Is there an upgrade guide for v1.8 to v3.x

**Comment by arpowers** [comment]
V3 is still unreleased technically, give us a couple weeks

**Comment by abishekrsrikaanth** [comment]
Cannot upgrade to v1.8.30 as I am having issues currently with v1.8.28 in regards to permalink. 
Unable to create posts, so looking forward to upgrading to the v3.x
