### ISSUE TITLE
Uknown file extension ".ts"

### ISSUE THREAD

**Issue by erossdev** [fictionco/fiction#288]
I'm a big fan from what I see of factor but I can't get it up and running (below is the error). I know you are doing a massive re-write and I was hoping to possibly contribute to the project but there are no guidelines or instructions to get up and running on my local machine.

```
> npx factor dev
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /Users/elliottross/projects/factor-hello-world/node_modules/@factor/cli/program.ts
    at new NodeError (internal/errors.js:322:7)
    at Loader.defaultGetFormat [as _getFormat] (internal/modules/esm/get_format.js:71:15)
    at Loader.getFormat (internal/modules/esm/loader.js:105:42)
    at Loader.getModuleJob (internal/modules/esm/loader.js:243:31)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Loader.import (internal/modules/esm/loader.js:177:17)
    at async file:///Users/elliottross/projects/factor-hello-world/node_modules/@factor/cli/cli.js:18:21 {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
```

**Comment by arpowers** [comment]
Correct, we're still building and refining things via work on Kaption.co ... Docs need to be updated. 

The probably you have above may be related to the version of Node you're using (should be 16+)...

**Comment by erossdev** [comment]
Even after upgrading to node 16 I'm still getting issues. First it complained there was no favicon.png which was easily fixed but now I'm getting 

` ERROR  Failed to resolve force included dependency: vuex`

Is there a public roadmap or will this only be developed in-house at kaption.co?

**Comment by arpowers** [comment]
The above issue looks like we need to add Vuex to a `package.json` somewhere.. Which repo are you trying to run? i'll update it.

Once Kaption is in production we will be updating the docs, and refining Factor for production use as a rapid GIT-powered CMS blogging/website creation engine.

Overall the issue is that the JS ecosystem best practices and tooling have been changing on a weekly basis.

**Comment by erossdev** [comment]
I tried doing a "getting started" from the factor website and create the minimum but doesn't seem to be working. If you have a minimal example that would be cool.

Agreed on the ecosystem! People always want the "latest cool thing" when it's not always the best...

Let me know if I can help in some way, feel free to close this issue too
